### ISSUE TITLE
Allow unregistered url to hit actual server 2

### ISSUE THREAD

**Issue by polosatyi** [pnuckowski/aioresponses#60]
Hi guys!

`passthrough` doesn't work for me

```
class SerpTopTestCase(AioHTTPTestCase):

    async def get_application(self):
        app = create_app(loop=self.loop)
        return app

    @unittest_run_loop
    async def test_serp_top(self):
        with aioresponses(passthrough=['https://api.vertifire.com']) as mocked:
            mocked.get(
                VERTIFIRE_SERP_TOP_API_URL, status=200, payload=dict(data=[]))
            request = await self.client.request("GET", "/serp_top/")
            assert request.status == 200
            response_data = await request.json()
            assert "data" in response_data
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/test_utils.py", line 415, in new_func
    return self.loop.run_until_complete(func(self))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/share/marketmuse/marketmuse/tests/functional/serp_top.py", line 165, in test_serp_top
    request = await self.client.request("GET", "/serp_top/")
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/test_utils.py", line 253, in request
    method, self.make_url(path), *args, **kwargs
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 616, in __iter__
    resp = yield from self._coro
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/aioresponses/core.py", line 170, in _request_mock
    if url.startswith(prefix):
AttributeError: 'URL' object has no attribute 'startswith'
```

what am I doing wrong?

ubuntu 14.04 
aiohttp==2.0.7
aioresponses==0.1.4

**Comment by pnuckowski** [comment]
I assume that you are using aiohttp to create web server, that expose some endpoint.
And endpoint "/serp_top/" actually make request to external service "https://api.vertifire.com".
I'm correct ?

If so, then you have to split your test.

`aiohttp.test_utils.TestClient` object (self.client in test) under the neath uses the `ClientSession` to perform request to your web server. What aioresponses does is it mocks some method in the `ClientSession` class. So it's not possible or harder to combine aioresponses together with aiohttp  webserver in test. `aioresponses` was not designed to cooperate with `aiohttp.web.Application`

What you can do is to have two methods: first method `serp_rop_request_handler `  will be request handler for "/serp_top/" in your web server and the second one `get_top_api` that actually hit external server.

example below

```python

# web.py
from path.to.vertifire import get_top_api

async def serp_rop_request_handler(request):
    top_data = await get_top_api()
    return web.Response(data=top_data)

app = web.Application()
app.router.add_get('/serp_top/', serp_rop_request_handler)


# test_web.py
# ///    and test for it in
@unittest_run_loop
@patch('path.to.vertifire.get_top_api')
async def test_serp_top(self, mocked):
    # note that get_top_api is a coroutine so mock object must also return coroutine
    mocked.side_effect = asyncio.coroutine(lambda *args, **kwargs: dict(data="it could be anything"))

    request = await self.client.request("GET", "/serp_top/")
    assert request.status == 200
    response_data = await request.json()
    assert "data" in response_data
```
And method and test that gets data from external service

```python
# vertifire.py

async def get_top_api():
    # todo: try except in case of 404 or 500 or connection refused....
    session = ClientSession()
    resp = await session.get(VERTIFIRE_SERP_TOP_API_URL)
    # process response and extract data
    resp.raise_for_status()   
    data = await resp.json()
    return data


# test_vertifire.py

async def test_correct_response_from_verfire(self):
    with aioresponses() as m:
        m.get(VERTIFIRE_SERP_TOP_API_URL, status=200, payload=dict(data='some data'))
       
        result = await get_top_api()

async def test_bad_response_from_verfire(self):
    with aioresponses() as m:
        m.get(VERTIFIRE_SERP_TOP_API_URL, status=404)
        with self.assertRaises( ClientResponseError ):
            await get_top_api()

```

So at the end you do not have to use `passthrough` since it's unittest and you decide what should be returned by external service in your tests.

I hope it helps you.
In case of further questions feel free to ask them :) 

PS. sorry for late response.

**Comment by pnuckowski** [comment]
But if you don"t want to split into two methods....

TestClient before making request transform "/serp_top/" into "http://127.0.0.1:{random_port}/serp_top/".


```python
async def test_with_web_server():
    # since test web server starts random port on localhost
    with aioresponses(passthrough='http://127.0.0.1') as m:
       m.get(VERTIFIRE_SERP_TOP_API_URL, status=200, payload=dict(data='some data'))
       request = await self.client.request("GET", "/serp_top/")

       assert request.status == 200
       response_data = await request.json()
       assert "data" in response_data
```
this will work in next version of aioresponses after I fix issue with `AttributeError: 'URL' object has no attribute 'startswith'`

**Comment by polosatyi** [comment]
@pnuckowski Thank you very much! I'll split into two methods. Thank you for your explanation!
But it will be great if you fix `AttributeError: 'URL' object has no attribute 'startswith'` in the future.

**Comment by pnuckowski** [comment]
Closing issue. 
New version [0.1.5](https://pypi.python.org/pypi/aioresponses/0.1.5) released 💥 🎉
